### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 9: ordinal not in range(128)

### ISSUE THREAD

**Issue by bmillham** [bmillham/DJDB#1]
Reported by zoschel:

a Traceback,
Getting catalogs
Traceback (most recent call last):
File "/home/ralf/Vorlagen/DJDB-master/LibScan/init.py", line 153, in scan_files
if self.check_tags(r, info):
File "/home/ralf/Vorlagen/DJDB-master/LibScan/init.py", line 252, in check_tags
res.append(self.check_item(db_row, 'artist_short', info.artist.name))
File "/home/ralf/Vorlagen/DJDB-master/LibScan/init.py", line 272, in check_item
self.add_changes(db_row['sid'], db_row['file'], db_key, tag, db_row[db_key])
File "/home/ralf/Vorlagen/DJDB-master/LibScan/init.py", line 374, in add_changes
self._changed_iters[id] = csa(None, (id, file, tag, str(filetag), str(dbtag)))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 9: ordinal not in range(128)

**Comment by bmillham** [comment]
Added a Python 2.7 hack to make it default to UTF8.

**Comment by bmillham** [comment]
Since I haven't heard back from the PR, I'm considering this as fixed.
